name: "Bug report:"
description: "File a bug report"
title: "[Bug report]: "
labels: ["bug"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: "Describe the bug:"
      description: Please provide information on the bug along with any relevant context.
    validations:
      required: true
  - type: textarea
    id: reproduce-step
    attributes:
      label: "Steps to reproduce the bug :"
      description: Please provide steps to reproduce this bug behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
    validations:
      required: true
  - type: dropdown
    id: device-type
    attributes:
      label: Please select your device type.
      multiple: true
      options:
        - Mobile
        - Desktop
        - Tablet
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshot / Screen Recording
      description: If available, add relevant media files here that help explains this issue.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Relevant log output
      description: Add any other context about the problem here.

  - type: checkboxes
    id: terms
    attributes:
      label: Issue Checklist
      options:
        - label: I have checked the existing [issues](https://github.com/TeamShiksha/events-frontend/issues) and made sure no duplicate issue exists.
          required: true
        - label: I want to work on this issue.
