name: "New Feature"
description: "Issue for new feature request"
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: "Describe the feature:"
      description: A clear and concise description of this new feature.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Issue Checklist
      options:
        - label: I have checked the existing [issues](https://github.com/TeamShiksha/events-frontend/issues) and made sure no duplicate issue exists for this new feature.
          required: true
        - label: I want to work on this issue.
